### ISSUE TITLE
Cannot run on Ubuntu 16.04 or 16.10

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/devices.ubports.com#11]
Node, being the fast-moving target that it is, will no longer build and run this site. I've tested only on Ubuntu 16.04 and 16.10, maybe someone can confirm in earlier versions.

Attached here are the npm debug log and the output of the `npm start` command.

[npm-debug.txt](https://github.com/ubports/devices.ubports.com/files/650707/npm-debug.txt)
[npmstart.txt](https://github.com/ubports/devices.ubports.com/files/650708/npmstart.txt)

**Comment by NeoTheThird** [comment]
@mariogrip Can you provide an updated build guide?

**Comment by NeoTheThird** [comment]
Fixed in 0766ed6bb72f8d2bb26585d955e57de6b8417cf7.
