### ISSUE TITLE
add link to bug tracker for each device

### ISSUE THREAD

**Issue by lduboeuf** [ubports/devices.ubports.com#17]
would be nice to have in each devices the corresponding bug tracker

**Comment by Flohack74** [comment]
Erm can you be more specific, just on the web page, or somewhere IN the device itself?

**Comment by lduboeuf** [comment]
yes in each device, by adding a category like "about device" where we can find link to bug tracker, sources, support, etc..

**Comment by NeoTheThird** [comment]
Good idea, wanted to do this earlier, but could not get around to it yet.

**Comment by NeoTheThird** [comment]
@mariogrip Can you restart the servers so the changes become active?
