### ISSUE TITLE
Implement "headers" on .devices.ubports.com

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/devices.ubports.com#9]
From [original issue](https://github.com/ubports/devices/issues/1), by @3rdwiki:

We need the "Active Devices", "Inprogress Devices", and "Voting Devices"

as 'Headers' so that we can say do the WebLink:

1. https://devices.ubports.com/#Core_Devices
2. https://devices.ubports.com/#Legacy_Devices
3. https://devices.ubports.com/#Development_Devices

(and the link goes to that 'section' of the devices.ubports.com/#/ web-page).

**Comment by molikmiah** [comment]
is this still an open issue? and is there still a bounty on it?

**Comment by UniversalSuperBox** [comment]
Go right ahead, We're still open @molikmiah !

**Comment by molikmiah** [comment]
@UniversalSuperBox just to make sure i have a good understanding of the requirements from this issue:
1 - if a user visits, for example, "https://devices.ubports.com/#Inprogress_Devices" they will expect to be taken to the "Devices" section of the website and auto-scrolls down to bring "In Progress Devices" into focus?

Or are you wanting to have new sections on the websites to represent each of the 3 categories?

**Comment by UniversalSuperBox** [comment]
The first one is correct, at least to my knowledge. @3rdwiki any different requirement?

**Comment by molikmiah** [comment]
@UniversalSuperBox i can't seem to get the project running locally, i think there might be missing dependencies in the package.json file such as "node-uuid" which is required in models/index.js but not declared as a dependency in the package.json

**Comment by UniversalSuperBox** [comment]
Yeah... See issue https://github.com/ubports/devices.ubports.com/issues/11

I have no experience what's going on with Node so I'd need a spare afternoon to even understand how the packaging format works. :)

**Comment by molikmiah** [comment]
Ok thanks @UniversalSuperBox, thats the same issue i came across. I'll have a look through the commit history tomorrow and see if i can find what files went missing. I'm sure we can have this back up and running :)

**Comment by 3rdwiki** [comment]
@UniversalSuperBox Yes the first one is correct, cheers.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/ubports.com#36
